<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu Site</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-color: #f4f4f4;
            padding: 50px;
        }
        .container {
            max-width: 400px;
            margin: auto;
            background: white;
            padding: 20px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        input {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
        }
        button {
            background-color: #28a745;
            color: white;
            padding: 10px;
            border: none;
            cursor: pointer;
            width: 100%;
        }
        button:hover {
            background-color: #218838;
        }
    </style>
</head>
<body>
    <h1>Bem-vindo ao Meu Site!</h1>

    <div class="container">
        <h2>Cadastrar Usu치rio</h2>
        <input type="text" id="newUser" placeholder="Usu치rio">
        <input type="password" id="newPass" placeholder="Senha">
        <button onclick="register()">Cadastrar</button>
    </div>

    <div class="container">
        <h2>Login</h2>
        <input type="text" id="username" placeholder="Usu치rio">
        <input type="password" id="password" placeholder="Senha">
        <button onclick="login()">Entrar</button>
    </div>

    <div class="container">
        <h2>Pesquisar</h2>
        <input type="text" id="searchBox" placeholder="Digite para pesquisar...">
        <button onclick="search()">Pesquisar</button>
    </div>

    <script>
        let users = {};

        function register() {
            let newUser = document.getElementById("newUser").value;
            let newPass = document.getElementById("newPass").value;

            if (newUser && newPass) {
                users[newUser] = newPass;
                alert("Usu치rio cadastrado com sucesso!");
            } else {
                alert("Preencha todos os campos!");
            }
        }

        function login() {
            let user = document.getElementById("username").value;
            let pass = document.getElementById("password").value;
            
            if (users
